- sql_dump.sql
-adding .sql dump of current DB version
> Create database and provide .sql dump

- project/controller/loginController.php
- project/controller/massRegistrationController.php
- project/controller/newRunController.php
- project/controller/singleRegistrationController.php
- project/database/routeUtils.php
- project/database/runUtils.php
- project/database/userUtils.php
- project/database/verificationUtils.php
- project/security/EmailVerificationHash.php
- project/security/passwordHash.php
- project/security/randomPassword.php
- project/services/csvRegistrationService.php
- project/services/loginCheckService.php
- project/services/printMapService.php
- project/services/progressBarService.php
- project/services/saveUserService.php
- project/services/sendEmailService.php
- project/templates/checkYourEmail.php
- project/templates/login.php
- project/templates/massRegisterPage.php
- project/templates/register.php
- project/utils/EmaiValidator.php
- project/utils/constructVerificationEmailContent.php
- project/utils/emailFormValidator.php
- project/utils/sendVerificationEmail.php
- project/utils/sessionUtils.php
Creates template how functions are connected and how calls are made internally
-resolves #34
> Create starting template

- project/config/config.php
- project/controller/fakeDbFillController.php
- project/database/createConnection.php
-adding two roles, USER -> id 1 / ADMIN -> id 2
-adding one admin and one user
resolves #53
> Add DB data fill for testing

- project/config/config.php
- project/controller/fakeDbFillController.php
- project/database/createConnection.php
- project/database/routeUtils.php
> Save route to DB

- project/database/userUtils.php
-adding function, that calls DB and either returns userID or null
if user is not present
365c88ae348c129d4c20b55f349c7f0382008e26 resolves #10
> Check if user is in DB

- project/controller/newRunController.php
- project/database/runUtils.php
- project/utils/sessionUtils.php
- sql_dump.sql
-adding logic to save run to DB
-adding new fields to DB so we can save run
-creating testing function in session utils to test for case
when user is not logged in
resolves #30
> Save new run to DB

- project/controller/emailVerificationController.php
- project/database/userUtils.php
- project/database/verificationUtils.php
- project/security/EmailVerificationHash.php
- project/security/passwordHashGenerator.php
- project/security/randomPasswordGenerator.php
- project/security/saltGenerator.php
- project/utils/constructVerificationEmailContent.php
- project/utils/sendVerificationEmail.php
-creating emailVerificationController.php, which handles email links
that were send to activate email
-adding function to activate user account
-adding function to check whether user account is activated
-adding function to save account verification hash and userID to DB
-adding function that get user account verification hash, given userID
-adding logic to security functions
-updating function that construct account verification email to include
link to emailVerificationController.php
> Email verification handling + security functions

- project/controller/massRegistrationController.php
- project/controller/singleRegistrationController.php
- project/services/saveUserService.php
- project/services/sendEmailService.php
- project/utils/constructVerificationEmailContent.php
- created method responsible for sending activation emails to users saved from CSV file
- added password to activation email (mainly because of mass CSV registration with generated passwords)
> Mass CSV registration - email sending to successfully saved users

- project/constants/routeConstants.php
- project/controller/newRouteController.php
- add controller for new route, to be called from site, where we create
new route
resolves #50
> New route controller

- project/static/style.css
- project/templates/login.php
- project/templates/massRegisterPage.php
-created a base visuals for whole site
-page can be accessed only if user is admin, else redirect to "login.php"
-removed error
-created horizontal menu bar
-on the menu bar are listed only proper options (user cant see admins options)
> Base for site visuals&mass register page

- project/database/routeUtils.php
- adding function to get top N contributors for routeID
- adding function to get last N run for routeID
- adding function that calculated total distance, remaining distance
and distance that was done
resolves #43 and resolves #44
Will provide changed sql dump later, _related issue_ #79
> Route utils

- project/controller/massRegistrationController.php
- project/database/userUtils.php
- project/services/csvRegistrationService.php
- project/services/saveUserService.php
- project/template_utils/tableGenerator.php
- created methods to display table with each CSV user with email and status
- added saveUserWithAdditionalData() method to saveUserService.php to be called within csvRegistrationService.php
- added association "FAILURE_REASON" to produced user data array (from CSV parsing in csvRegistrationService.php) in case user fails to be saved  - partially resolves #14 
- added table generating method to template_utils, resolving #78
> Mass CSV registration - table creation

- project/controller/massRegistrationController.php
- project/services/csvRegistrationService.php
- project/static/ajaxCsvFileUpload.js
- project/templates/homePage.php
- project/templates/massRegisterPage.php
- project/utils/sessionUtils.php
- csv file now upload async - via ajax - to be able to print the results table to origin template
- minor changes in templates
> CSV file upload update

- project/database/routeUtils.php
-adding fake function to simulate return value from DB
> All routes interface design

- project/controller/newRouteController.php
- project/database/routeUtils.php
- project/services/printRoutesTableService.php
- sql_dump.sql
-adding new parameters to newRouteController.php, name and coordinates
-adding new function to get route data for user, based on visibility
-adding new function, to get route data for admin
-adding SQL dump
> Route logic work

- project/controller/newRunController.php
- project/database/userUtils.php
- project/utils/sessionUtils.php
-small sql fix with finding active route
> Small SQL fix

- project/database/teamUtils.php
- sql_dump.sql
-adding tables related to team to DB
-adding function to save team to DB
-adding function to get teamID from team name
-adding function to check if team name is already in DB
-adding function to get team into based on teamID
-adding function to get teamID from routeID (if exists)
-adding fake function to simulate all teams in DB
resolves #99 and resolves #100 and resolves #97
> Team Database Utils

- project/database/teamUtils.php
- project/database/userUtils.php
- sql_dump.sql
-fixing small bug in get team info function
-adding function to get all teams data
-adding function to add route to team
resolves #102 and resolves #101 and resolves #79
> Team utils work + New table News in DB

- project/database/userUtils.php
-adding function to get one user based on userID
-adding function to get every user in DB
> Get all users

- project/controller/loginController.php
- project/controller/singleRegistrationController.php
- project/database/teamUtils.php
- project/database/userUtils.php
- project/services/loginCheckService.php
-changing logic to take into account real functions
-fixing small bug in singleRegistrationController.php
-refactoring code for new method addUserToTeam
-adding function to get UserRole from DB
> Various small fixes

- project/controller/loginController.php
- project/database/teamUtils.php
- project/utils/sessionUtils.php
-adding deleteUserFromTeam function
-fixing small login issues
> Small login fixes

- project/static/addNewsStyle.css
- project/static/allTeamStyle.css
- project/static/style.css
- project/templates/allTeams.php
- project/templates/homePage.php
- project/templates/massRegisterPage.php
> -created fronted for allTeams.php

- project/services/progressBarService.php
- project/templates/homePage.php
-adding progress bar service logic
> Progress bar service

- project/database/routeUtils.php
-adding logic to get short description from DB
-adding logic to get full description from DB
-adding related functions to count contributors and get route mode
> Route utils work

- project/services/printRoutesTableService.php
- project/services/printTeamsTableService.php
- project/utils/sessionUtils.php
- replaced db util calls in table generating services to _FAKE methods temporarily
> FAKE update for Libor

- project/database/userUtils.php
-adding fake user stats function
> Fake user stats function

- project/database/userUtils.php
-adding logic to get every run + route name to which it contributes
from DB
resolves #155
> Every run for user

- project/database/routeUtils.php
- project/database/userUtils.php
-adding function to check, if route is visible for USER. Does not take
into account that user could be ADMIN, as that should be handled in
service calling this method.
> Route visibility

- project/sql_dump.sql
-prefilling DB with roles and route types
resolves #138
> Prefill DB

- osoby2.csv
- project/services/csvRegistrationService.php
-changing encoding from ASCII to UTF-8
> Fixed .csv encoding

- project/controller/massRegistrationController.php
- project/services/csvRegistrationService.php
- project/template_utils/menuGenerator.php
-fixing small things all around
> Micro fixes

- project/database/addressUtils.php
-fixing missing reference when saving user via mass registration
> Fixed missing DB reference to address

- project/static/addTableParameters.js
- project/static/newsStyle.css
- project/templates/allRoutes.php
- project/templates/allUsersStatsPage.php
- project/templates/userStatsPage.php
- project/utils/sessionUtils.php
-like sorting of tables
-too long rows in some tables
> matus-rybar-fixes-stuff

- project/services/printNewsService.php
- project/templates/newsPage.php
- changed template to only giving link to next page if there are news available
- resolves #169
> news update

- project/controller/newRouteController.php
- project/controller/newRunController.php
- project/database/routeUtils.php
- project/database/userUtils.php
- project/security/passwordHashGenerator.php
- project/services/printRoutesTableService.php
- project/utils/sessionUtils.php
-adding logic to save team route
-adding function to get routeID from team name
-adding function t ge route contributors
> Various bug fixes + new team save logic

- project/database/routeUtils.php
-fixed missing routeID in all routes link to single route page
> Missing routeID in link

- project/database/routeUtils.php
- project/services/progressBarService.php
-adding function to print team color bar
> Team progress bar

- project/database/routeUtils.php
- project/services/singleRouteServices.php
- project/templates/homePage.php
- project/templates/singleRouteDetail.php
-fixing routes having negative remaining distance
-fixing team visibility SQL select
> Fixes all around

- project/database/routeUtils.php
- project/services/printUserSelectService.php
- project/services/progressBarService.php
- project/templates/homePage.php
> Small fix to save GPS coords

- project/services/printAllUsersTableService.php
- project/services/printUsersStatsTableService.php
> Removing fake functions

- project/controller/emailVerificationController.php
- project/controller/singleRegistrationController.php
- project/database/verificationUtils.php
- project/security/EmailVerificationHash.php
- project/services/printUsersStatsTableService.php
- project/templates/checkYourEmail.php
- project/utils/constructVerificationEmailContent.php
> user accout activation fuckery

- project/services/progressBarService.php
> Fixed progress bar
